#Ayer Config

menu:

# https://github.com/mattboldt/typed.js
subtitle:
  enable: false
#  text: HI!!!  # 面朝大海，春暖花开 # 显示的文字
#  text2: 愿你一生努力，一生被爱 # 滚动播放，如果不需要可以留空
#  text3: 想要的都拥有，得不到的都释怀 # 最多支持三段文字
  startDelay: 0 
  typeSpeed: 100
  loop: true
  backSpeed: 100
  showCursor: true

# logo
favicon: /Logo-blue.svg #icon on browser tab
logo: /images/Logo-white.svg #logo in sidebar menu

cover:
  enable: false
  path: /images/cover2.jpg # /source/images
  logo: false #/Logo-blue.svg，false

progressBar: true

broadcast:
  enable: false # true，false
  type: 2 # 1：，2：一api(https://hitokoto.cn/)
 # text: 一个安静优雅的hexo主题，快速且响应式。

# excerpt_link: 阅读更多...
excerpt_all: false

copy_btn: true
share_enable: true
# (If you are not in China, maybe you prefer to set:false)
share_china: false
share_text: Share

nav_text:
  page_prev: Previous Page
  page_next: Next Page
  post_prev: Older Posts
  post_next: Newer Posts

toc: true

image_viewer: true

# https://github.com/willin/hexo-wordcount
# Front-matter no_word_count: true
word_count:
  enable: false
  only_article_visit: true


copyright_type: 2

#hexo-generator-searchdb(https://github.com/theme-next/hexo-generator-searchdb)
search: true

# RSS hexo-generator-feed config
# rss: /atom.xml

darkmode: true

canvas_bg: 0

mouse:
  enable: false
  path: /images/mouse.cur

click_effect: 0

layout:
  article_width: 80rem
  sidebar_width: 8rem

# GitHub Ribbons

music:
  enable: false
  type: 1
  id: 22707008
  autoPlay: true

# Google Analytics
# google_analytics: ""
# baidu_analytics: ""

# Mathjax
mathjax: false

# Katex (allpost false math:true)
# hexo，npm un hexo-renderer-marked -S && npm i hexo-renderer-markdown-it-katex -S
katex:
  enable: false # true
  allpost: true
  copy_tex: false

# mermaid (https://mermaid-js.github.io/mermaid/)
mermaid:
  enable: false
 # cdn: https://cdn.staticfile.org/mermaid/8.14.0/mermaid.min.js
  theme: forest

since: 2022

friends_link:

# 1、Valine；2、Gitalk；3、Twikoo; 4.MiniValine

# 1、Valine (https://github.com/xCss/Valine)
leancloud:
  enable: false
  app_id: #
  app_key: #
# Valine
valine:
  enable: false 
  avatar: monsterid # (https://valine.js.org/avatar.html)
#  placeholder: 给我的文章加点评论吧~ # placeholder

# 2、Gitalk(https://github.com/gitalk/gitalk)

# 4、MiniValine
# See: https://github.com/MiniValine/MiniValine
minivaline:
  enable: false
  #  https://minivaline.js.org/docs/cn/#/Options
  # emoticonUrl https://github.com/MiniValine/hexo-next-minivaline
  # serverURL: https://minivaline.your-domain.com

lock:
  enable: false
  password: 123456
